  1. Побудуйте ER-діаграму вашої бази даних у будь-якому зручному
//     інструменті — dbdiagram.io, draw.io, Lucidchart тощо.

// Вставте ваш DBML-код нижче 👇

Table locations {
  location_id int [pk, increment]
  name varchar(50) [not null]
  address varchar(50) [not null]
  city varchar(50) [not null]
  }

Table staff {
  staff_id int [pk, increment]
  first_name varchar(50) [not null]
  last_name varchar(50) [not null]
  role varchar(50) [not null]
  phone varchar(20)
  emain varchar(100) [unique]
  location_id int [not null]
}

Ref: staff.location_id > locations.location_id

Table menu_items {
  item_id int [pk, increment]
  name varchar(100) [not null]
  category varchar(50) [not null]
  price decimal(100,2) [not null]
  preparation_time int 
  description varchar(255)
}

Table orders {
  order_id int [pk, increment]
  order_number varchar(20) [unique, not null]
  order_type varchar(20) [not null]
  status varchar(20) [not null]
  location_id int [not null]
  order_date datetime [not null]
}
Ref: orders.location_id > locations.location_id

Table order_items {
  order_item_id int [pk, increment]
  order_id int [not null]
  item_id int [not null]
  quantity int [not null]
  unit_price decimal(10,2) [not null]
}

Ref: order_items.order_id > orders.order_id
Ref: order_items.item_id > menu_items.item_id


Table basic_inventory {
  inventory_id int [pk, increment]
  item_name varchar(100) [not null]
  quantity decimal(10,2) [not null]
  unit varchar(20) [not null]
  location_id int [not null]
}

Ref: basic_inventory.location_id > locations.location_id
